scalar Time
scalar DeletedAt

interface Base {
  "#orm:pk"
  id: ID!
  createdAt: Time!
  updatedAt: Time!
  deletedAt: DeletedAt
}

enum Status {
  Active
  Deactivated
  Blocked
  Draft
  Pending
  Closed
}
