type Todo implements Base {
  "#orm:pk"
  id: ID!
  createdAt: Time!
  updatedAt: Time!
  deletedAt: DeletedAt

  name: String!

  "#orm:default:false"
  completed: Boolean

  user: User!

  userID: ID!
}

input CreateTodoInput {
  name: String!
  completed: Boolean
  userID: ID!
}

extend type Mutation {
  createTodo(todo: CreateTodoInput!): Todo
}

extend type Query {
  todos: [Todo]
}
