type User implements Base {
  id: ID!
  createdAt: Time!
  updatedAt: Time!
  deletedAt: DeletedAt
  email: String
  phone: String
  password: String
  token: String
}

input CreateUserInput {
  email: String
  phone: String
  password: String
}

input UpdateUserInput {
  id: ID!
  email: String
  phone: String
  password: String
}

extend type Query {
  users: [User]
}

extend type Mutation {
  createUser(user: CreateUserInput!): User
  updateUser(user: UpdateUserInput!): User
}
