// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package model

import (
	"time"
)

type Base interface {
	IsBase()
}

type User struct {
	ID        string     `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	Email     *string    `json:"email"`
	Phone     *string    `json:"phone"`
	Password  *string    `json:"password"`
}

func (User) IsBase() {}
