// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

type Base interface {
	IsBase()
}

type User struct {
	ID        string          `json:"id"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	DeletedAt *gorm.DeletedAt `json:"deletedAt"`
	Email     *string         `json:"email"`
	Phone     *string         `json:"phone"`
	Password  *string         `json:"password"`
	Active    *bool           `json:"active"`
}

func (User) IsBase() {}
