database:
  host: dev.fastme.net
  port: 5432
  user: nimer_farahty
  password: ******
  database: go_lang

server:
  port: 3000

security:  
  refreshToken:
    expiry: 5h
    secret: jlwjdlwjldjwlkdjlwdrgergfewgf
  accessToken:
    expiry: 5m
    secret: lhlkhdlwhdhwlkdnwlkndw
