// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"gorm.io/gorm"
)

type Base interface {
	IsBase()
}

type CreatePostInput struct {
	Title    string  `json:"title"`
	AuthorID *int    `json:"authorId"`
	Body     *string `json:"body"`
}

type CreateTodoInput struct {
	Name      string `json:"name"`
	Completed *bool  `json:"completed"`
	OwnerID   int    `json:"ownerID"`
}

type CreateUserInput struct {
	Email    *string `json:"email"`
	Phone    *string `json:"phone"`
	Password *string `json:"password"`
}

type LoginInput struct {
	Identity string `json:"identity"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User   *User   `json:"user"`
	Tokens *Tokens `json:"tokens"`
}

type Post struct {
	ID        int             `json:"id" gorm:"type:serial;primaryKey"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	DeletedAt *gorm.DeletedAt `json:"deletedAt" gorm:"index"`
	Title     string          `json:"title"`
	Body      *string         `json:"body"`
	Author    *User           `json:"author"`
	AuthorID  int             `json:"authorId"`
}

func (Post) IsBase() {}

type Todo struct {
	ID        int             `json:"id" gorm:"type:serial;primaryKey"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	DeletedAt *gorm.DeletedAt `json:"deletedAt" gorm:"index"`
	Name      string          `json:"name"`
	Completed *bool           `json:"completed" gorm:"default:false"`
	Owner     *User           `json:"owner"`
	OwnerID   int             `json:"ownerID"`
}

func (Todo) IsBase() {}

type Tokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type UpdateUserInput struct {
	ID       int     `json:"id"`
	Email    *string `json:"email"`
	Phone    *string `json:"phone"`
	Password *string `json:"password"`
}

type User struct {
	ID        int             `json:"id" gorm:"type:serial;primaryKey"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	DeletedAt *gorm.DeletedAt `json:"deletedAt" gorm:"index"`
	Email     *string         `json:"email"`
	Phone     *string         `json:"phone"`
	Password  *string         `json:"password"`
	Token     *string         `json:"token"`
	Todos     []*Todo         `json:"todos" gorm:"foreignKey:OwnerID"`
	Posts     []*Post         `json:"posts" gorm:"foreignKey:AuthorID"`
}

func (User) IsBase() {}

type Status string

const (
	StatusActive      Status = "Active"
	StatusDeactivated Status = "Deactivated"
	StatusBlocked     Status = "Blocked"
	StatusDraft       Status = "Draft"
	StatusPending     Status = "Pending"
	StatusClosed      Status = "Closed"
)

var AllStatus = []Status{
	StatusActive,
	StatusDeactivated,
	StatusBlocked,
	StatusDraft,
	StatusPending,
	StatusClosed,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusActive, StatusDeactivated, StatusBlocked, StatusDraft, StatusPending, StatusClosed:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
