// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Base interface {
	IsBase()
}

type CreateUserInput struct {
	Email    *string `json:"email"`
	Phone    *string `json:"phone"`
	Password *string `json:"password"`
}

type UpdateUserInput struct {
	ID       uuid.UUID `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	Email    *string   `json:"email"`
	Phone    *string   `json:"phone"`
	Password *string   `json:"password"`
}

type User struct {
	ID        uuid.UUID       `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	DeletedAt *gorm.DeletedAt `json:"deletedAt" gorm:"index"`
	Email     *string         `json:"email"`
	Phone     *string         `json:"phone"`
	Password  *string         `json:"password"`
	Token     *string         `json:"token"`
}

func (User) IsBase() {}
